name: "mfedattoio-monica-crm"

x-common-props: &common-props
  restart: "unless-stopped"
  dns:
    - "1.1.1.1"
    - "4.4.4.4"
  environment:
    PUID: "1000"
    PGID: "1000"
    TZ: "America/Sao_Paulo"
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:

  mfedattoio-monica-app:
    <<: *common-props
    image: "monica"
    container_name: "mfedattoio-monica-app"
    hostname: "mfedattoio-monica-app"
    environment:
      APP_KEY: "${APP_KEY}"
      DB_HOST: "mfedattoio-monica-db"
      DB_DATABASE: "${MONICA_DB_NAME}"
      DB_USERNAME: "${MONICA_DB_USER}"
      DB_PASSWORD: "${MONICA_DB_PASSWORD}"
      MAIL_FROM_ADDRESS: "${MAIL_USERNAME}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
      MAIL_DRIVER: "${MAIL_DRIVER}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
    volumes:
      - "mfedattoio-monica-app-storage:/var/www/html/storage"
    networks:
      stack-net:
      mfedattoio-vpc-net:
    ports:
      - "8781:80"
    depends_on:
      - "mfedattoio-monica-db"

  mfedattoio-monica-db:
    <<: *common-props
    image: "mariadb:11"
    container_name: "mfedattoio-monica-db"
    hostname: "mfedattoio-monica-db"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "${MONICA_DB_NAME}"
      MYSQL_USER: "${MONICA_DB_USER}"
      MYSQL_PASSWORD: "${MONICA_DB_PASSWORD}"
    volumes:
      - "mfedattoio-monica-db-data:/var/lib/mysql"
    networks:
      stack-net:
      mfedattoio-db-net:

networks:
  stack-net:
    driver: "bridge"
  mfedattoio-vpc-net:
    external: true
  mfedattoio-db-net:
    external: true

volumes:
  mfedattoio-monica-app-storage:
    external: true
  mfedattoio-monica-db-data:
    external: true
